env = Environment(CCFLAGS = '-O2')
system = ARGUMENTS.get('system', 0)
if int(system):
    env.Append(CCFLAGS = ' -DDEFAULT_DIC_PATH=\\"/usr/share/wxscrab/dic/ods8.dico\\"')

gen_part = env.Program(['gen_part.c','bag.c','board.c', 'board_cross.c', 'board_search.c', 'dic.c',
    'game.c', 'getopt.c', 'pldrack.c', 'rack.c', 'results.c',
    'round.c', 'tiles.c'])
listdic = env.Program(['listdic.c', 'dic.c'])
compdic = env.Program(['compdic.c', 'hashtable.c'])
swapdic = env.Program(['swapdic.c'])

env.Install('/usr/bin', gen_part)
env.Install('/usr/bin', listdic)
env.Install('/usr/bin', compdic)
env.Install('/usr/bin', swapdic)

env.Alias('install', '/usr/bin')
